myrubychina/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('rubychina.urls')),
]

rubychina/urls.py
from django.conf.urls import url

from . import views
from .views import auth

app_name = 'rubychina'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^articles$', views.articles, name="articles"),
    url(r'^login$', auth.Login.as_view(), name="login"),
    url(r'^logout$', auth.user_logout, name="logout"),
    url(r'^register$', auth.Register.as_view(), name="register"),
]

rubychina/models.py
from __future__ import unicode_literals

from django.db import models

class Node(models.Model):
    node_name = models.CharField(max_length=200)
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField('date created')
    modify_date = models.DateTimeField('date modified')

    def __str__(self):
        return self.node_name

class Article(models.Model):
    title = models.CharField(max_length=300)
    content = models.CharField(max_length=30000)
    node = models.ForeignKey(Node, on_delete=models.CASCADE)
    create_date = models.DateTimeField('date created')
    pub_date = models.DateTimeField('date published')
    modify_date = models.DateTimeField('date modified')

    def __str__(self):
        return self.title


  

rubychina/templates/articles.html
{% extends 'extends/base.html' %}

{% block title %}
Articles
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">Articles</div>
          {% if articles %}
          <ul class="list-group">
            {% for article in articles %}
            <li class="list-group-item">{{article.title}}</li>
            {% endfor %}
          </ul>
          {% else %}
          <div class="panel-body">
            <p> no articles at all</p>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

rubychina/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-6">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>
    {% block title %}MySite{% endblock %}
    </title>

    <!-- Bootstrap -->
    <link href="static/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}
    {% endblock %}
  </head>
  <body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">MySite</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li {% if current_view == 'index' %}class="active"{% endif %}>
          <a href="{% url 'rubychina:index' %}">
          Index <span class="sr-only">(current)</span>
          </a>
        </li>
        <li {% if current_view == 'articles' %}class="active"{% endif %}>
          <a href="{% url 'rubychina:articles' %}">
            Articles
          </a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if not user.is_authenticated %}
        <li><a href="{% url 'rubychina:login' %}?next={{ current_view }}">Login</a></li>
        {% endif %}
        {% if user.is_authenticated %}
        <li>
          <a href="javaScript:void(0)">
          Welcome,
          {{user.username}}
          </a>
        </li>
        <li><a href="{% url 'rubychina:logout' %}?current_view={{ current_view }}">Logout</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% if messages %}
<ul class="messages text-success">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="container-fluid">
  {% block content %}
  {% endblock %}
</div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="static/jquery/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="static/bootstrap-3.3.7/js/bootstrap.min.js"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

rubychina/templates/extends/base.html
{% extends 'extends/skeleton.html' %}

{% block body %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">MySite</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li {% if current_view == 'index' %}class="active"{% endif %}>
          <a href="{% url 'rubychina:index' %}">
          Index <span class="sr-only">(current)</span>
          </a>
        </li>
        <li {% if current_view == 'articles' %}class="active"{% endif %}>
          <a href="{% url 'rubychina:articles' %}">
            Articles
          </a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if not user.is_authenticated %}
        <li><a href="{% url 'rubychina:login' %}?next={{ current_view }}">Login</a></li>
        <li><a href="{% url 'rubychina:register' %}?next={{ current_view }}">Register</a></li>
        {% endif %}

        {% if user.is_authenticated %}
        <li>
          <a href="javaScript:void(0)">
          Welcome,
          {{user.username}}
          </a>
        </li>
        <li><a href="{% url 'rubychina:logout' %}?current_view={{ current_view }}">Logout</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% include 'includes/messages.html' %}

<div class="container-fluid">
  {% block content %}
  {% endblock %}
</div>
{% endblock %}

rubychina/templates/extends/skeleton.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-6">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>
    {% block title %}MySite{% endblock %}
    </title>

    <!-- Bootstrap -->
    <link href="static/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}
    {% endblock %}
  </head>
  <body>
    {% block body %}
    {% endblock %}
    <script src="static/jquery/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="static/bootstrap-3.3.7/js/bootstrap.min.js"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

rubychina/templates/includes/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li
    {% if message.tags %} class="{{ message.tags }}" {% endif %}
    >
    {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

rubychina/templates/index.html
{% extends 'extends/base.html' %}

{% block title %}
Index
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">Latest Articles</div>
          {% if latest_articles %}
          <ul class="list-group">
            {% for article in latest_articles %}
            <li class="list-group-item">{{article.title}}</li>
            {% endfor %}
          </ul>
          {% else %}
          <div class="panel-body">
            <p> no articles at all</p>
          </div>
          {% endif %}
        </div>
      </div>
    <div class="col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">Latest Nodes</div>
          <div class="panel-body">
            {% if latest_nodes %}
            <div class="btn-group">
            {% for node in latest_nodes %}
            <button class="btn btn-default" type="button">{{node.node_name}}</button>
            {% endfor %}
            </div>
            {% else %}
            <p> no nodes at all</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
{% endblock %}

rubychina/templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="utf-6">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Login</title>

    <!-- Bootstrap -->
    <link href="static/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Login
                    </div>
                    <div class="panel-body">
                        <form action="/login" method="POST" class="form">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{next}}"/>
                            <div class="form-group">
                                <label for="username" class="control-label">user</label>
                                <input type="text" id="username" name="username" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password" class="control-label">password</label>
                                <input type="password" name="password" id="password" class="form-control">
                            </div>
                            {% if error %}
                            <div class="form-group text-danger">
                                {{error}}
                            </div>
                            {% endif %}
                            <div class="form-group">
                                <button class="btn btn-primary" type=submit>
                                    Submit
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="static/jquery/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="static/bootstrap-3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

rubychina/templates/register.html
{% extends 'extends/skeleton.html' %}

{% block title %}Register{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Register
                    </div>
                    <div class="panel-body">
                        <form action="/register" method="POST" class="form">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{next}}"/>
                            <div class="form-group">
                                <label for="username" class="control-label">user</label>
                                <input type="text" id="username" name="username" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password" class="control-label">password</label>
                                <input type="password" name="password" id="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="confirm-password" class="control-label">confirm password</label>
                                <input type="password" name="confirm-password" id="confirm-password" class="form-control">
                            </div>
                            {% if error %}
                            <div class="form-group text-danger">
                                {{error}}
                            </div>
                            {% endif %}
                            <div class="form-group">
                                <button class="btn btn-primary" type=submit>
                                    Submit
                                </button>
                            </div>
                            {% include 'includes/messages.html' %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}